<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="ILRepacker" AfterTargets="Build">
        <ItemGroup>
		    <InputAssemblies Include="$(OutputPath)$(AssemblyName).dll" />
			<InputAssemblies Include="$(OutputPath)Community.CsharpSqlite.dll" />
			<InputAssemblies Include="$(OutputPath)Community.CsharpSqlite.SQLiteClient.dll" />
		</ItemGroup>
		<ItemGroup>
			<LibraryPath Include="$(GameDirectory)\Beat Saber_Data\Managed\" />
			<LibraryPath Include="$(GameDirectory)\Beat Saber_Data\Libs\" />
			<LibraryPath Include="$(GameDirectory)\Plugins\" />
			<LibraryPath Include="$(OutputPath)\" />
		</ItemGroup>

        <ILRepack
            Parallel="true"
            InputAssemblies="@(InputAssemblies)"
			LibraryPath="@(LibraryPath)"
			Verbose="true"
			LogFile="$(OutputPath)ILRepack.log"
            TargetKind="Dll"
            OutputFile="$(OutputPath)\$(AssemblyName).dll"
        />
    </Target>
</Project>